# Use the official Apache image as the base image
FROM httpd:2.4

# Copy the index.html file to the Apache web server directory
COPY index.html /usr/local/apache2/htdocs/

# Expose port 80 for HTTP traffic
EXPOSE 80

# The default command to run when the container starts
CMD ["httpd-foreground"]